import type { NextPage } from 'next'
import Head from 'next/head'
import { Contacts } from '../conteiners/contacts'
import { Footer } from '../conteiners/footer'
import { Header } from '../conteiners/header'
import { Sightseens } from '../conteiners/sightseens'
import { Tours } from '../conteiners/tours'
import { Welcome } from '../conteiners/welcome'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Amatic+SC&family=Roboto:wght@100;300;400;500;700&display=swap&subset=cyrillic-ext" rel="stylesheet"></link>
        <script src="https://unpkg.com/react-yandex-maps/dist/production/react-yandex-maps.umd.js"></script>
      </Head>
      
      <body>  
        <Header/>

        <main>
          <Welcome/>
          <Sightseens/>
          <Tours/>
          <Contacts/>
          <Footer/>
        </main>
      </body>

    </div>
  )
}

export default Home
